export const DEFAULT_COUNTRY = "India";

/** Common country names for address Select. India is first (default). */
export const COUNTRY_OPTIONS = [
  "India",
  "United Arab Emirates",
  "United States",
  "United Kingdom",
  "Singapore",
  "Saudi Arabia",
  "Nepal",
  "Bangladesh",
  "Sri Lanka",
  "Australia",
  "Canada",
  "Germany",
  "France",
  "China",
  "Japan",
  "Malaysia",
  "Thailand",
  "Indonesia",
  "Oman",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "South Africa",
  "New Zealand",
  "Netherlands",
  "Italy",
  "Spain",
  "Switzerland",
  "Hong Kong",
  "South Korea",
];
