/**
 * Quotation form configuration — sections, initial state, and constants.
 * Do not filter productMake by productType; Make is universal.
 */

/** Section key, product type name(s) for display_order, and title. */
export const TECHNICAL_SECTIONS = [
    { key: "structure", typeNames: ["structure"], title: "Structure" },
    { key: "panel", typeNames: ["panel"], title: "Panel" },
    { key: "inverter", typeNames: ["inverter"], title: "Inverter" },
    { key: "battery", typeNames: ["battery"], title: "Battery" },
    { key: "hybridInverter", typeNames: ["hybrid inverter"], title: "Hybrid Inverter" },
    { key: "acdb", typeNames: ["acdb"], title: "ACDB" },
    { key: "dcdb", typeNames: ["dcdb"], title: "DCDB" },
    { key: "cable", typeNames: ["ac cable", "dc cable"], title: "Cable" },
    { key: "earthing", typeNames: ["earthing"], title: "Earthing" },
    { key: "la", typeNames: ["la"], title: "LA (Lightning Arrester)" },
    { key: "additionalDescriptions", typeNames: [], title: "Additional Descriptions" },
];

/** Default accordion expanded state by section key */
export const DEFAULT_EXPANDED_ACCORDIONS = {
    structure: true,
    panel: true,
    inverter: true,
    battery: false,
    hybridInverter: false,
    acdb: true,
    dcdb: true,
    cable: true,
    earthing: true,
    la: true,
    additionalDescriptions: true,
};

/**
 * Build initial form state. Pass user and optional overrides.
 */
export function getInitialFormData(user, overrides = {}) {
    const today = new Date().toISOString().split("T")[0];
    const validTill = new Date(new Date().setDate(new Date().getDate() + 15)).toISOString().split("T")[0];

    return {
        quotation_number: "",
        quotation_date: today,
        valid_till: validTill,
        user_id: user?.id ?? "",
        branch_id: "",
        inquiry_id: "",
        customer_id: "",
        customer_name: "",
        mobile_number: "",
        email: "",
        company_name: "",
        state_id: "",
        address: "",
        order_type_id: "",
        project_scheme_id: "",
        project_price_id: "",
        project_capacity: "",
        price_per_kw: "",
        total_project_value: "",
        structure_amount: "",
        subsidy_amount: "",
        state_subsidy_amount: "",
        netmeter_amount: "",
        stamp_charges: "",
        state_government_amount: "",
        discount_type: "",
        discount: "",
        gst_rate: "",
        additional_cost_details_1: "",
        additional_cost_amount_1: "",
        additional_cost_details_2: "",
        additional_cost_amount_2: "",
        structure_product: "",
        structure_height: "",
        structure_material: "",
        panel_product: "",
        panel_size: "",
        panel_quantity: "",
        panel_make_ids: [],
        panel_type: "",
        panel_warranty: "",
        panel_performance_warranty: "",
        inverter_product: "",
        inverter_size: "",
        inverter_quantity: "",
        inverter_make_ids: [],
        inverter_warranty: "",
        hybrid_inverter_product: "",
        hybrid_inverter_size: "",
        hybrid_inverter_quantity: "",
        hybrid_inverter_make_ids: [],
        hybrid_inverter_warranty: "",
        battery_product: "",
        battery_size: "",
        battery_quantity: "",
        battery_make_ids: [],
        battery_type: "",
        battery_warranty: "",
        acdb_product: "",
        acdb_quantity: "",
        acdb_description: "",
        dcdb_product: "",
        dcdb_quantity: "",
        dcdb_description: "",
        cable_ac_product: "",
        cable_ac_quantity: "",
        cable_ac_make_ids: [],
        cable_ac_description: "",
        cable_dc_product: "",
        cable_dc_quantity: "",
        cable_dc_make_ids: [],
        cable_dc_description: "",
        earthing_product: "",
        earthing_quantity: "",
        earthing_make_ids: [],
        earthing_description: "",
        la_product: "",
        la_quantity: "",
        la_make_ids: [],
        la_description: "",
        earthing_description_text: "",
        lightening_arrester_description_text: "",
        mis_description: "",
        battery_description_text: "",
        system_warranty_years: "",
        payment_terms: "",
        remarks: "",
        graph_price_per_unit: "",
        graph_per_day_generation: "",
        graph_yearly_increment_price: "",
        graph_yearly_decrement_generation: "",
        project_cost: "",
        total_payable: "",
        effective_cost: "",
        ...overrides,
    };
}
