// utils/iconMapper.js
// Maps icon name strings to Tabler icon components (@tabler/icons-react)

import {
  IconHome,
  IconCalendar,
  IconMessageCircle,
  IconShoppingCart,
  IconPlayerPlay,
  IconCirclePlus,
  IconPackage,
  IconSettings,
  IconUsers,
  IconShield,
  IconApps,
  IconLink,
  IconMapPin,
  IconUserPlus,
  IconCategory,
  IconBuilding,
  IconBox,
  IconReceipt,
  IconCurrencyDollar,
  IconFileDescription,
  IconLayoutDashboard,
  IconBinaryTree,
  IconFolder,
  IconList,
  IconTool,
  IconBuildingStore,
  IconChartBar,
  IconCreditCard,
  IconTruckDelivery,
  IconUserCog,
  IconUsersGroup,
  IconShieldCheck,
  IconLayoutGrid,
  IconUser,
  IconBell,
  IconMail,
  IconPhone,
  IconMessage,
  IconTrendingUp,
  IconCash,
  IconBuildingBank,
  IconReceipt2,
  IconPackageExport,
  IconBuildingWarehouse,
  IconTag,
  IconStar,
  IconCircleCheck,
  IconCircleX,
  IconAlertTriangle,
  IconAlertCircle,
  IconInfoCircle,
  IconHelp,
  IconSearch,
  IconFilter,
  IconDownload,
  IconUpload,
  IconPrinter,
  IconShare,
  IconPencil,
  IconTrash,
  IconPlus,
  IconDeviceFloppy,
  IconEye,
  IconLock,
  IconUserCircle,
  IconBriefcase,
  IconBuildingCommunity,
  IconMap,
  IconClock,
  IconCalendarEvent,
  IconChecklist,
  IconCloud,
  IconDatabase,
  IconFolderOpen,
  IconPhoto,
  IconFileTypePdf,
  IconFileText,
  IconNotes,
  IconHistory,
  IconTimeline,
  IconRefresh,
  IconRefreshDot,
  IconMenu2,
  IconListNumbers,
  IconLayoutList,
  IconLayoutKanban,
  IconTable,
  IconGridDots,
  IconClipboardList,
} from "@tabler/icons-react";

const iconMap = {
  home: IconHome,
  dashboard: IconLayoutDashboard,
  calendar: IconCalendar,
  leads: IconMessageCircle,
  inquiry: IconMessageCircle,
  order: IconShoppingCart,
  execution: IconPlayerPlay,
  quick_service: IconCirclePlus,
  procurement: IconPackage,
  settings: IconSettings,
  users: IconUsers,
  user: IconUsers,
  roles: IconShield,
  role: IconShield,
  modules: IconApps,
  module: IconApps,
  role_modules: IconLink,
  "role-modules": IconLink,
  closed_orders: IconCircleCheck,
  "closed-orders": IconCircleCheck,
  inquiry_management: IconMessageCircle,
  "inquiry-management": IconMessageCircle,
  site_visit: IconMapPin,
  "site-visit": IconMapPin,
  followup: IconUserPlus,
  masters: IconCategory,
  company_profile: IconBuilding,
  "company-profile": IconBuilding,
  product: IconBox,
  bill_of_materials: IconReceipt,
  "bill-of-materials": IconReceipt,
  bill_of_material: IconReceipt,
  "bill-of-material": IconReceipt,
  project_price_list: IconCurrencyDollar,
  "project-price-list": IconCurrencyDollar,
  project_price: IconCurrencyDollar,
  "project-price": IconCurrencyDollar,
  quotation: IconFileDescription,
  task_planner: IconCalendar,
  "task-planner": IconCalendar,
  marketing_leads: IconMessageCircle,
  "marketing-leads": IconMessageCircle,
  order_management: IconShoppingCart,
  "order-management": IconShoppingCart,
  execution_planner: IconPlayerPlay,
  "execution-planner": IconPlayerPlay,
  add_quick_service: IconCirclePlus,
  "add-quick-service": IconCirclePlus,
  folder: IconFolder,
  list: IconList,
  build: IconTool,
  store: IconBuildingStore,
  assessment: IconChartBar,
  payment: IconCreditCard,
  shipping: IconTruckDelivery,
  engineering: IconTool,
  manage: IconUserCog,
  group: IconUsersGroup,
  admin: IconShieldCheck,
  view_module: IconLayoutGrid,
  account: IconUser,
  tree: IconBinaryTree,
  notifications: IconBell,
  email: IconMail,
  phone: IconPhone,
  chat: IconMessage,
  message: IconMessage,
  analytics: IconChartBar,
  bar_chart: IconChartBar,
  chart: IconChartBar,
  trending_up: IconTrendingUp,
  report: IconChartBar,
  money: IconCash,
  account_balance: IconBuildingBank,
  credit_card: IconCreditCard,
  receipt: IconReceipt2,
  inventory2: IconPackageExport,
  warehouse: IconBuildingWarehouse,
  offer: IconTag,
  discount: IconTag,
  star: IconStar,
  check_circle: IconCircleCheck,
  success: IconCircleCheck,
  cancel: IconCircleX,
  warning: IconAlertTriangle,
  error: IconAlertCircle,
  info: IconInfoCircle,
  help: IconHelp,
  search: IconSearch,
  filter: IconFilter,
  download: IconDownload,
  upload: IconUpload,
  print: IconPrinter,
  share: IconShare,
  edit: IconPencil,
  delete: IconTrash,
  add: IconPlus,
  save: IconDeviceFloppy,
  visibility: IconEye,
  lock: IconLock,
  person: IconUser,
  supervisor: IconUserCog,
  work: IconBriefcase,
  domain: IconBuildingCommunity,
  map: IconMap,
  schedule: IconClock,
  event: IconCalendarEvent,
  task: IconChecklist,
  checklist: IconChecklist,
  cloud: IconCloud,
  storage: IconDatabase,
  folder_open: IconFolderOpen,
  image: IconPhoto,
  pdf: IconFileTypePdf,
  article: IconFileText,
  note: IconNotes,
  history: IconHistory,
  timeline: IconTimeline,
  refresh: IconRefresh,
  sync: IconRefreshDot,
  menu: IconMenu2,
  view_list: IconListNumbers,
  view_kanban: IconLayoutKanban,
  view_table: IconTable,
  view_grid: IconGridDots,
  assignment: IconClipboardList,
  campaign: IconMessageCircle,
};

/**
 * Get all valid icon names
 */
export const getValidIconNames = () => Object.keys(iconMap);

/**
 * Check if an icon name is valid
 */
export const isValidIcon = (iconName) => {
  if (!iconName) return false;
  const normalized = iconName
    .toLowerCase()
    .trim()
    .replace(/\s+/g, "_")
    .replace(/-/g, "_");
  return iconMap.hasOwnProperty(normalized) || iconMap.hasOwnProperty(iconName.toLowerCase());
};

/**
 * Get Tabler icon component by name. Returns a component that accepts className (e.g. "h-5 w-5").
 */
export const getIcon = (iconName) => {
  if (!iconName) return IconSettings;
  const normalized = iconName
    .toLowerCase()
    .trim()
    .replace(/\s+/g, "_")
    .replace(/-/g, "_");
  return iconMap[normalized] || iconMap[iconName.toLowerCase()] || IconSettings;
};

/**
 * Get all available icon names for the icon picker
 */
export const getAvailableIcons = () => {
  const entries = [
    ["home", "Home", IconHome],
    ["dashboard", "Dashboard", IconLayoutDashboard],
    ["menu", "Menu", IconMenu2],
    ["inquiry", "Inquiry", IconMessageCircle],
    ["order", "Order", IconShoppingCart],
    ["quotation", "Quotation", IconFileDescription],
    ["procurement", "Procurement", IconPackage],
    ["product", "Product", IconBox],
    ["bill_of_materials", "Bill of Materials", IconReceipt],
    ["project_price", "Project Price", IconCurrencyDollar],
    ["company_profile", "Company Profile", IconBuilding],
    ["calendar", "Calendar", IconCalendar],
    ["task_planner", "Task Planner", IconCalendar],
    ["schedule", "Schedule", IconClock],
    ["event", "Event", IconCalendarEvent],
    ["task", "Task", IconChecklist],
    ["checklist", "Checklist", IconChecklist],
    ["execution", "Execution", IconPlayerPlay],
    ["site_visit", "Site Visit", IconMapPin],
    ["followup", "Followup", IconUserPlus],
    ["map", "Map", IconMap],
    ["leads", "Leads", IconMessageCircle],
    ["users", "Users", IconUsers],
    ["user", "User", IconUser],
    ["roles", "Roles", IconShield],
    ["modules", "Modules", IconApps],
    ["settings", "Settings", IconSettings],
    ["masters", "Masters", IconCategory],
    ["payment", "Payment", IconCreditCard],
    ["money", "Money", IconCash],
    ["inventory", "Inventory", IconPackage],
    ["warehouse", "Warehouse", IconBuildingWarehouse],
    ["store", "Store", IconBuildingStore],
    ["add", "Add", IconPlus],
    ["edit", "Edit", IconPencil],
    ["delete", "Delete", IconTrash],
    ["search", "Search", IconSearch],
    ["filter", "Filter", IconFilter],
    ["view_list", "View List", IconListNumbers],
    ["view_kanban", "View Kanban", IconLayoutKanban],
    ["list", "List", IconList],
    ["folder", "Folder", IconFolder],
  ];
  return entries.map(([name, label, component]) => ({
    name,
    label,
    component,
    category: "General",
  }));
};

export default getIcon;
